### ISSUE TITLE
Reject data from a bot when there is already an entry for the browser_version on a given test

### ISSUE THREAD

**Issue by clopez** [Igalia/browserperfdash#12]
I tested to send data twice using the same browser_version for the benchmark kraken for the bot buildbox3.

I was expecting the data to be rejected on the second try, but it was accepted:

https://browserperfdash.igalia.com/dash/report/detail/151451
https://browserperfdash.igalia.com/dash/report/detail/151496

https://people.igalia.com/clopez/browser_perf_dash_browserversionrepeated.png

It doesn't really make sense to have different results for a given browser_version/bot/test.

So, when we receive data from a bot for a given test, we should check if we already have a data entry for the reported browser_version. And in that case return an error to the bot and ignore the new data that the bot was sending.

**Comment by tonythomas01** [comment]
Maybe I can add a `unique` rule for (`bot`, `browser`, `browser_version`, `root_test`, `test_path`, `test_version`)

**Comment by tonythomas01** [comment]
Deplyong that change would be breaking, and possibly I will have to truncate the `botreport_data`. 

I also see that adding that kind of a unique can affect on peformance, but it seems like to affect only the write operation, which I guess should be fine.

**Comment by tonythomas01** [comment]
wiped the db, the constrained should now work.
