### ISSUE TITLE
`cumulative regressions/improvments` table for the dashboard

### ISSUE THREAD

**Issue by tonythomas01** [Igalia/browserperfdash#2]
`(01:21:58  CET) Carlos López: but if we have [10,9,8,7,6,5,4,3,2,1].. then will you able to detect that in the last 10 days we had a >90% regression altought from day-to-day it was only a 10%?` 

The logic for a cumulative regression for `n` days should be: 
`value[today]-value[today-n]`% or is there something I am missing here ? The intermediate values are not to be considered right ? 

if this is the case, we can get that straightaway with a single query (with subqueries) though (current value - previous value). 

Once the aim of the task gets clear, I will get to implement the same.

**Comment by tonythomas01** [comment]
@clopez: ^^

**Comment by clopez** [comment]
I think we can forget about cumulative values.

It makes more sense to get the regression data only from version(n) to version(n-1)
