### ISSUE TITLE
Migrate codebase to Python 3

### ISSUE THREAD

**Issue by tonythomas01** [Igalia/browserperfdash#20]
We have couple of failing cases with https://github.com/Igalia/browserperfdash/blob/master/dashboard/helpers/benchmark_results.py which needs to be fixed for travis to run successfully.

**Comment by tonythomas01** [comment]
I got a confusing case testing out the case in https://trac.webkit.org/browser/trunk/Tools/Scripts/webkitpy/benchmark_runner/benchmark_results_unittest.py?rev=216117#L51. 

The data in question is: 
```
SomeTest:Time:Arithmetic: 3.0ms stdev=33.3%
	        :Time:Total: 7.0ms stdev=28.6%
	        SubTest1:Time: 2.0ms stdev=50.0%
	        SubTest2:Time: 5.0ms stdev=20.0%

```
as you can see - the Arithmetic mean should be (2+5)/2 = 3.5 - which python3 correctly calculates. But python2 takes it more lightly by: 
`>>(2+5)/2 = 3`

causing for an error in result. Do you think I should fix it in the benchmark class, or add an int() parse to the function so that we ignore the floats ? I personally think we should not ignore this though.

**Comment by tonythomas01** [comment]
@clopez: Well - post ^^ change, we are completely broken in python 2.x, but working on https://travis-ci.org/Igalia/browserperfdash. I want your confirmation on https://github.com/Igalia/browserperfdash/issues/20#issuecomment-299590794 before deploying it to our server though.

**Comment by tonythomas01** [comment]
now that I think about it, I would go forward and deploy the same eitherway, as the change is revertible anyday by adding in an int() to the arithmetic mean calculations.

**Comment by tonythomas01** [comment]
Done and deployed at https://browserperfdash.igalia.com/

**Comment by clopez** [comment]
@tonythomas01 [On python2 the operator division (/) defaults to int. On python 3 it defaults to float.](http://stackoverflow.com/questions/21316968/division-in-python-2-7-and-3-3)

* Example with python2 (see how it defaults to int)
```
In [1]: (2+5)/2
Out[1]: 3
In [2]: type((2+5)/2)
Out[2]: int
```

There are two possible fixes for this:

1.  Import the division operator from _future_ (the one used on python 3)
      1.1. Example with python2:
```
In [1]: from __future__ import division
In [2]: (2+5)/2
Out[2]: 3.5
In [3]: type((2+5)/2)
Out[3]: float
```

2. Be explicit with the types of the operands passed to division:
      2.1. Example with python2:
```
In [1]: float(2+5)/float(2)
Out[2]: 3.5
In [2]: type(float(2+5)/float(2))
Out[2]: float
```

**Comment by tonythomas01** [comment]
Alright. So - I can conclude that its alright to have the float() result from the division operation. Since we have that already, I would close this one as done. 

We are not supporting python 2.X anymore anyway - hence I dont think we will have to do the separate division thing for compatiability.
