### ISSUE TITLE
Enable automatic db backup  of application database

### ISSUE THREAD

**Issue by tonythomas01** [Igalia/browserperfdash#24]
We have multiple options here -https://django-dbbackup.readthedocs.io/en/stable/storage.html 

if we have some amazon database account, then it would be the best though. @clopez  ^^ need your inputs here.

**Comment by clopez** [comment]
I think the application doesn't really need to take care of this. The sysadmins deploying the service should do it.

We usually set up a cronjob that does a daily pg_dumpall to /var/backups and then we have another cronjob that syncs all the contents on the server (also daily) to off-site storage.

**Comment by tonythomas01** [comment]
nic . No worries on this then.
