### ISSUE TITLE
The "add bot" view on the admin page doesn't show the name of the cpu/gpu/platform objects

### ISSUE THREAD

**Issue by clopez** [Igalia/browserperfdash#28]
When adding a new bot on the admin-page in the drop-down menu to select the cpu, gpu or platform objects instead of the name of the object it simply shows "CPUArchitecture Object", or "GPUType Object" or "Platform Object".

So the admin doesn't know which one should select when there are more than one possibility.

See screenshot of problem here: https://people.igalia.com/clopez/dashissues/field_name_admin.png

**Comment by tonythomas01** [comment]
Should be fixed by adding a 
```
def __str__() to the models. 
```
See: https://stackoverflow.com/questions/9336463/django-xxxxxx-object-display-customization-in-admin-action-sidebar

**Comment by tonythomas01** [comment]
Tested, fixed in #29
