### ISSUE TITLE
Metric prefix/scale not correctly implemented on admin interface

### ISSUE THREAD

**Issue by clopez** [Igalia/browserperfdash#5]
On the design document, where it defines how to add new units there is the field metric-prefix.

https://en.wikipedia.org/wiki/Metric_prefix

This is not intended to be a simple text-field, but it should be something like an editable table that allows the admin to set different metric prefixes and the number of base units for each prefix.

So, if for some benchmark i have something that yields 3660030 milliseconds, the application can use that info to automatically (at runtime) convert that to something more readable like:

`3660030 milliseconds == 1 hour, 1 minute and 30 millisecond
`

To illustrate better how I imagine the admin interface for inputting such data I have quickly crafted a rudimentary example.

This is how it looks now: http://people.igalia.com/clopez/example_metrics/metric_time.html
This is how I would like it to look: http://people.igalia.com/clopez/example_metrics/metric_timev2.html

For implementing the table I used some pretty basic/rudimentary javscript. Probably something better and with better look can be done using some of this modern JS frameworks. Here are some links with inspiration ideas:

The application should validate the input, For example, it makes no sense to introduce anything non numeric in the second field.
And then store this metric scale-prefixes somewhere, and then decide if it makes sense to display the value in the basic unit or better it should display the value scaling it to some of this prefixes. 

The rule of thumb will be to use the higher scale value possible, meanwhile the scaled value on that scale is >1.

So, for 999 value of time i would display: 999 ms and for 1000 value of time i would display: 1 sec. For 1001 value of time I would display: 1 second and 1 ms.

This is a low-priority task.
Lets keep it open for the moment. 
We can start working on this when the rest of the application is more finished.

**Comment by tonythomas01** [comment]
I think I might be able to solve this thing with the Django `ArrayField`. Trying it out now. https://docs.djangoproject.com/en/1.10/ref/contrib/postgres/fields/#arrayfield

**Comment by tonythomas01** [comment]
I can put this thing as a JSON field and live with it, but I still dont get where we would be showing this. Like as a popover in the dashboard results table on hovering values ?

**Comment by tonythomas01** [comment]
Finally ended up making 
![image](https://cloud.githubusercontent.com/assets/4214481/24981164/a72bfc06-1fdb-11e7-8b16-62abd8d4814d.png)

:)

**Comment by tonythomas01** [comment]
The menu is now deployed at https://browserperfdash.igalia.com/admin/dashboard/metricunit/ btw.

**Comment by tonythomas01** [comment]
and I pushed in the frontend patch too. I should say that the new calculations have slowed down things a bit, but - we cannot avoid it, right. We will need more botreport data there to actually make things show up on the website.

![browser performance dashboard - google chrome_417](https://cloud.githubusercontent.com/assets/4214481/25074755/5d155f74-2303-11e7-9e41-32334921f916.png)

**Comment by tonythomas01** [comment]
Well. I noticed that we can save on this processing time by doing the calucations at the backend (on reception of bot data). Will change that likewise, to save precious processing time.

**Comment by tonythomas01** [comment]
Closing this thing down, as we have the `metric_units` implemented on the admin panel!
