### ISSUE TITLE
Improvements on the data that is displayed on the tables

### ISSUE THREAD

**Issue by clopez** [Igalia/browserperfdash#7]
I think the std.dev information on the tables is not useful. Neither is very useful the test version.

On the other hand I miss seeing the previous and current values.

I would like to have a more concise and useful information. 

This is an example of the kind of table I would like to see:

```
| Delta | Browser         | Revision range  | Bot         | Test                 | Values in both revisions | Metric             |
|-------|-----------------|-----------------|-------------|----------------------|--------------------------|--------------------| 
| 44%   | chrome-canary   | 42024  -  42181 | buildbox    | SunSpider:regexp-dna | 23 ms      -       20 ms | Time (down_arrow)  |
|-------|-----------------|-----------------|-------------|----------------------|--------------------------|--------------------| 
| 31%   | minibrowser-gtk | r12810 - r12918 | gtkbot      | Kraken:total         | 23.45 pt   -    27.89 pt | Score (up_arrow)   |
|-------|-----------------|-----------------|-------------|----------------------|--------------------------|--------------------| 
```
                                            

Then, I would like the following to happen:

 * If the test version has changed between both revision ranges for a given row, then the test cell should have a red background color, and when you mouse over it a tooltip would appear saying that the test version has changed between both revisions. The tooltip also shows the test_id name.
   * Otherwise (the test version is the same between both revision ranges), no background color is set, and when the mouse moves over the test cell a tooltip appears showing the test version that was used for both versions. The tooltip also shows the test_id name.
 
 * When you mouse over the bot name on a cell, a tooltip should appear that details the platform, cpu and gpu info for that bot.
 
* The values in the "Values in both revisions" cell should be rounded to 2 decimals when shown and they should be suffixed with the metric unit. When you mouse over them, a tooltip appears that shows the stdev on the 2 revisions.

Note: in Metric where it says down_arrow and up_arrow I don't mean to write that text there, but to show an icon with an arrow looking to the top or to the bottom depending on the metric type (better_is_zero vs better_is_infinite)

**Comment by clopez** [comment]
Note: "revision" means the same than "version". 
When talking about browsers (specially about development snapshots built from the svn/git repository) is pretty common to refer to the browser version as the browser revision.

**Comment by tonythomas01** [comment]
There is a less expensive but hard coded way of doing this by adding in an extra field to the current bot_report table. This would be prev_revision, which would be foreign key for the previous test result (from which delta is calculated). So that we can get the data about previous thingy too realtime. Let me see how the resulting json would look like.

**Comment by tonythomas01** [comment]
Works as expected. Closing now.
