### ISSUE TITLE
Allow to receive a timestamp value in the bot POST parameters

### ISSUE THREAD

**Issue by clopez** [Igalia/browserperfdash#8]
Right now, when this web application receives some data from a bot it assumes _now_ is the timestamp for the data received.

That is fine, but we want also support an optional timestamp parameter that may let us do some clever things with the data we sent from the bots.

The idea is the following:

  * If in the POST parameters sent by the bot there isn't a timestamp parameter (like currently happens), the web application assumes the timestamp is _now_.
  * If the parameter sent by the bot contain a timestamp parameter, we use that timestamp instead of _now_. Such timestamp will be an integer, with an UTC Epoch stamp (number of seconds since 1 Jan 1970 on UTC timezone).
    ```
    In [1]: import time
    
    In [2]: int(time.time())
    Out[2]: 1485213331
    ```
  * In both cases, we check that the timestamp we got (either _now_ or the bot submitted value) is a numeric value and is higher than the last recorded timestamp.
      * If is not the case, then we return an error code.

**Comment by tonythomas01** [comment]
This should be fixed at this moment, we have 'timestamp' field added as a param, expecting data in `UTC`

**Comment by tonythomas01** [comment]
Works now.
